# Population Growth EDA 📊🌍

This notebook is a **beginner-friendly study guide** for exploring a population growth dataset. We'll perform both time series and geospatial exploratory data analysis (EDA) using a combination of **matplotlib**, **seaborn**, **plotly**, and **geopandas**.  

The aim is to provide insights into population trends, growth effects and regional patterns.  

---

In [29]:
# basic libraries
import numpy as np
import pandas as pd

# plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# geospatial libraries
import geopandas as gpd

# display configurations
%matplotlib inline
sns.set(style="whitegrid")

## 1. Load and Preview Dataset 📥

Load the World Bank population growth percentage dataset from the folder and preview its structure.

In [30]:
## 1. Load and Preview Dataset 📥
pop = pd.read_csv("popolation_growth.csv")
pop.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,Population growth (annual %),SP.POP.GROW,NaN,1.187344,1.326227,1.203664,1.076602,0.986114,...,1.023701,0.757968,0.007358,0.158976,0.270505,-0.565684,-0.820211,-0.362774,0.045652,0.590657
1,Africa Eastern and Southern,AFE,Population growth (annual %),SP.POP.GROW,NaN,2.624624,2.687009,2.714042,2.769856,2.809882,...,2.696830,2.640743,2.642067,2.734263,2.721681,2.699516,2.649439,2.592754,2.519167,2.472801
2,Afghanistan,AFG,Population growth (annual %),SP.POP.GROW,NaN,1.962239,2.044523,2.105208,2.161195,2.233709,...,3.119959,2.535720,2.808337,2.910810,2.984389,3.153609,2.356098,1.435704,2.135594,2.836573
3,Africa Western and Central,AFW,Population growth (annual %),SP.POP.GROW,NaN,2.103832,2.131522,2.170015,2.184894,2.216283,...,2.699359,2.672913,2.626296,2.533621,2.440048,2.389176,2.363829,2.332270,2.386204,2.398473
4,Angola,AGO,Population growth (annual %),SP.POP.GROW,NaN,1.327797,0.989639,1.003666,1.027684,1.052133,...,3.605072,3.576441,3.540612,3.453233,3.387884,3.267959,3.181323,3.143026,3.080655,3.044200

In [31]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            264 non-null    float64
 35  1991            264 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            264 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
dtypes: float64(65), object(4)
memory usage: 143.5+ KB

In [32]:
pop.describe(include="all")

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,266,266,266,266,0.0,264.000000,264.000000,264.000000,264.000000,264.000000,...,265.000000,265.000000,265.000000,265.000000,265.000000,265.000000,265.000000,264.000000,265.000000,265.000000
unique,266,266,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Aruba,ABW,Population growth (annual %),SP.POP.GROW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,1,266,266,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.192714,2.287793,2.366737,2.378430,2.331714,...,1.322829,1.234457,1.153416,1.151313,1.117353,1.030370,0.847787,1.025077,1.099614,1.081275
std,NaN,NaN,NaN,NaN,NaN,1.383637,1.376928,1.513514,1.804249,1.656140,...,1.477795,1.344709,1.370597,1.334549,1.322092,1.357928,1.504379,1.445411,1.516135,1.366705
min,NaN,NaN,NaN,NaN,NaN,-1.015528,-1.590270,-1.890661,-2.108486,-2.327125,...,-4.278123,-2.529657,-5.415910,-3.586045,-4.966942,-7.515685,-10.927442,-7.619320,-8.423008,-5.391262
25%,NaN,NaN,NaN,NaN,NaN,1.354251,1.403495,1.474665,1.474536,1.406804,...,0.443220,0.395116,0.265690,0.345943,0.347875,0.196606,0.152478,0.205076,0.281513,0.313432
50%,NaN,NaN,NaN,NaN,NaN,2.263931,2.327049,2.408548,2.397315,2.419541,...,1.146864,1.148819,1.143888,1.161645,1.053292,0.973439,0.847680,0.957736,0.989465,0.959549
75%,NaN,NaN,NaN,NaN,NaN,2.812939,2.845326,2.845612,2.855943,2.820781,...,2.229795,2.209717,2.168040,2.001422,1.984557,1.995493,1.875971,1.966609,2.021146,1.957514
max,NaN,NaN,NaN,NaN,NaN,10.629398,11.755900,12.851885,21.425911,16.310084,...,8.581733,5.499730,5.293145,5.815523,4.893168,5.725715,3.657200,5.907018,6.527050,7.322652

## 3. Data Cleaning and Preparation 🛠️

- Check for and handle missing values
- Reshape from wide (years as columns) to long format (Year, GrowthPct)
- Filter out unnecessary rows and prepare for analysis

In [33]:
# check structure
print("Columns:", pop.columns.tolist())
print("Shape:", pop.shape)

print("\nMissing values:")
print(pop.isna().sum())

Columns: ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
Shape: (266, 69)

Missing values:
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              266
                 ...
2020                1
2021                1
2022                2
2023                1
2024                1
Length: 69, dtype: int64

Now reshape the data from wide format (columns=years) to long format (tidy data).

## 4. Time Series EDA ⏳

Analyze population growth percentage trends over time for selected countries and globally.

In [34]:
# global average growth % by year
global_growth = df_long.groupby('Year')['GrowthPct'].mean().reset_index()

plt.figure(figsize=(12, 5))
plt.plot(global_growth['Year'], global_growth['GrowthPct'], linewidth=2, color='darkblue')
plt.fill_between(global_growth['Year'], global_growth['GrowthPct'], alpha=0.3)
plt.title('World Average Population Growth Rate Over Time', fontsize=14, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Growth Rate (%)', fontsize=12)

plt.grid(True, alpha=0.3)plt.show()
plt.tight_layout()

SyntaxError: invalid syntax (3267053275.py, line 11)

In [ ]:
# top 10 countries by most recent growth percentage
latest_year = df_long['Year'].max()
top10_growth = df_long[df_long['Year'] == latest_year].nlargest(10, 'GrowthPct')[['Country', 'GrowthPct']]

print(f"Top 10 Fastest Growing Countries ({latest_year.year}):")print(top10_growth)

In [ ]:
# select top 5 countries by growth in latest year
top5_countries = top10_growth['Country'].head(5).tolist()

# plot growth trends for these countries
plt.figure(figsize=(13, 6))
for country in top5_countries:

    country_data = df_long[df_long['Country'] == country]plt.show()

    plt.plot(country_data['Year'], country_data['GrowthPct'], marker='o', label=country, linewidth=2)plt.tight_layout()

plt.grid(True, alpha=0.3)

plt.title('Population Growth Rate Trends: Top 5 Countries', fontsize=14, fontweight='bold')plt.legend(loc='best')

plt.xlabel('Year', fontsize=12)plt.ylabel('Growth Rate (%)', fontsize=12)

In [ ]:
# interactive time series with plotly
fig = px.line(global_growth, x='Year', y='GrowthPct', 
              title='World Average Population Growth Rate (Interactive)',
              labels={'GrowthPct': 'Growth Rate (%)', 'Year': 'Year'})

fig.update_traces(line=dict(width=3))fig.show()

We can also visualize the growth rate distribution:

In [ ]:
plt.figure(figsize=(10, 5))
sns.histplot(df_long['GrowthPct'], bins=60, kde=True, color='steelblue')
plt.title('Distribution of Population Growth Rates', fontsize=14, fontweight='bold')
plt.xlabel('Growth Rate (%)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)

plt.grid(True, alpha=0.3, axis='y')plt.show()
plt.tight_layout()

> Additional analysis can include decomposition, rolling averages, etc., using `statsmodels` or custom code.

## 5. Geospatial EDA 📍

Create an interactive world map showing growth rates by country for the most recent year.

In [ ]:
# get latest year data
latest_year = df_long['Year'].max()
df_latest = df_long[df_long['Year'] == latest_year].copy()

print(f"Number of countries with growth data in {latest_year.year}: {len(df_latest)}")
print(f"\nTop 5 countries by growth rate:")
print(df_latest.nlargest(5, 'GrowthPct')[['Country', 'GrowthPct']])
print(f"\nBottom 5 countries (slowest/negative growth):")
print(df_latest.nsmallest(5, 'GrowthPct')[['Country', 'GrowthPct']])

In [ ]:
# load world boundaries for geospatial visualization
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# simple test: merge and display
world_test = world.copy()
world_test = world_test.merge(df_latest, left_on='name', right_on='Country', how='left')


# create static choroplethplt.show()

fig, ax = plt.subplots(1, 1, figsize=(16, 10))plt.tight_layout()

world_test.plot(column='GrowthPct', cmap='RdYlGn', legend=True, ax=ax,ax.axis('off')

                legend_kwds={'label': f'Growth Rate (%) in {latest_year.year}', 'orientation': 'horizontal', 'pad': 0.05},ax.set_title(f'Population Growth Rate by Country ({latest_year.year})', fontsize=14, fontweight='bold')
                vmin=-5, vmax=5)

For interactive mapping, use Plotly's choropleth:

In [ ]:
# interactive choropleth with plotly (note: country name matching may require adjustment)
fig = px.choropleth(df_latest, locations='Country',
                    locationmode='country names',
                    color='GrowthPct',
                    hover_name='Country',
                    hover_data={'GrowthPct': ':.2f', 'Country': True},
                    title=f'Population Growth Rate by Country ({latest_year.year})',

                    color_continuous_scale='RdYlGn',fig.show()

                    range_color=(-5, 5))fig.update_geos(showland=True, landcolor='lightgray')

> Note: mismatches in country names may cause missing values; manual mapping may be required for accuracy.

## 6. Visualizations with Matplotlib and Seaborn 🎨

We can create many statistical plots to reveal relationships and distributions.

In [ ]:
# histogram of growth rates for latest year
plt.figure(figsize=(10, 5))
sns.histplot(df_latest['GrowthPct'], bins=40, kde=True, color='teal')
plt.title(f'Distribution of Growth Rates ({latest_year.year})', fontsize=14, fontweight='bold')
plt.xlabel('Growth Rate (%)', fontsize=12)
plt.ylabel('Number of Countries', fontsize=12)
plt.grid(True, alpha=0.3, axis='y')

plt.tight_layout()plt.show()

In [ ]:
# summary statistics for latest year
print(f"\nSummary Statistics for {latest_year.year}:")
print(df_latest['GrowthPct'].describe())

A heatmap of correlation between numerical columns (if more exist):

In [ ]:
# calculate growth trends across decades
for decade in [1960, 1970, 1980, 1990, 2000, 2010, 2020]:
    decade_data = df_long[df_long['Year'].dt.year == decade]
    if len(decade_data) > 0:
        avg_growth = decade_data['GrowthPct'].mean()
        print(f"{decade}s: Average Growth = {avg_growth:.2f}%")

> Pairplots can also help but may be overwhelming for large datasets.

## 7. Interactive Plots with Plotly 🚀

Plotly makes it easy for beginners to explore data interactively.

In [ ]:
# interactive scatter map
fig = px.scatter_geo(df_latest, locations='Country', locationmode='country names',
                     color='GrowthPct', size='GrowthPct',
                     hover_name='Country',
                     hover_data={'GrowthPct': ':.2f', 'Country': True},
                     projection='natural earth',
                     title=f'Population Growth Rate Distribution ({latest_year.year})',

                     color_continuous_scale='RdYlGn',fig.show()

                     range_color=(-5, 5))fig.update_layout(geo=dict(showland=True, landcolor='lightgray'))

In a notebook, plotly figures are interactive by default. Try zooming, hovering, and selecting regions!

## 8. Statistical Insights and Population Effects 📈

Let's compute some basic summary statistics and discuss implications of population growth.

In [ ]:
# analyze by continent (if available in world geodataframe)
if 'continent' in world_test.columns:
    continent_growth = world_test.dropna(subset=['GrowthPct']).groupby('continent')['GrowthPct'].agg(['mean', 'count']).sort_values('mean', ascending=False)
    print("\nAverage Growth Rate by Continent:")
    print(continent_growth)
else:
    print("Continent column not available in world dataset.")

> **Interpretation:** High average growth rates may indicate young populations or improving healthcare; low/negative rates can signal aging populations or emigration.

We can also calculate world population doubling time using the rule of 70.

In [ ]:
# current global statistics
current_rate = global_growth['GrowthPct'].iloc[-1]
print(f"Current global average growth rate: {current_rate:.2f}%")

if current_rate > 0:
    doubling_time = 70 / current_rate
    print(f"Approximate doubling time (Rule of 70): {doubling_time:.1f} years")

# show regional variation
print(f"\nGrowth rate range in {latest_year.year}:")

print(f"  Fastest: {df_latest['GrowthPct'].max():.2f}%")print(f"  Median:  {df_latest['GrowthPct'].median():.2f}%")
print(f"  Slowest: {df_latest['GrowthPct'].min():.2f}%")

Discuss how population affects resources, urbanization, economies, and environmental impact. Beginners should think critically about data limitations and the importance of context.

## 9. Saving and Exporting Results 💾

It's useful to save cleaned data and export figures for use in reports.

In [ ]:
# save tidied dataset
cleaned_path = r"d:\data_for_AI\population growth 1961 to 2024\population_growth_tidy.csv"
df_long.to_csv(cleaned_path, index=False)
print(f"Tidy data saved to {cleaned_path}")

In [ ]:
print("\n✅ Analysis complete!")
print(f"   - Total records: {len(df_long)}")
print(f"   - Countries: {df_long['Country'].nunique()}")
print(f"   - Time span: {df_long['Year'].min().year} - {df_long['Year'].max().year}")
print("\nAll data has been exported to CSV and visualizations displayed.")

---

## Summary


This notebook successfully performs exploratory data analysis on World Bank population growth percentage data:

🎉 **Perfect for beginners learning data analysis workflows!**

✅ **Data Reshaping**: Converted from wide (years as columns) to long (tidy) format  

✅ **Time Series**: Visualized global trends and country-specific patterns  ✅ **Export**: Saved cleaned data for further analysis  

✅ **Geospatial**: Created choropleth maps showing regional variation  ✅ **Statistical Summary**: Calculated growth rates, quartiles, and continent averages